# Generated by ChatGPT - manual migration example
from django.db import migrations, models
import django.db.models.deletion


def copy_question_subjects(apps, schema_editor):
    Question = apps.get_model('app', 'Question')
    Test = apps.get_model('app', 'Test')
    Subject = apps.get_model('app', 'Subject')
    # copy test.subject into m2m field
    for t in Test.objects.all():
        if t.subject_id:
            try:
                subj = Subject.objects.get(id=t.subject_id)
                t.subjects.add(subj)
            except Subject.DoesNotExist:
                pass
    # assign question.subject when missing
    for q in Question.objects.all():
        if q.subject_id is None and q.test_id:
            try:
                t = Test.objects.get(id=q.test_id)
                if t.subject_id:
                    q.subject_id = t.subject_id
                    q.save(update_fields=['subject'])
            except Test.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='point_value',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text="Savol uchun to‘g‘ri javob bo‘lganda qancha ball qo‘shilishini belgilaydi", max_digits=4, verbose_name="Ball qiymati"),
        ),
        migrations.AddField(
            model_name='test',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tests', to='app.Subject'),
        ),
        # ensure existing subject FK on Test allows null
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.AddField(
            model_name='result',
            name='weighted_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.RunPython(copy_question_subjects, reverse_code=migrations.RunPython.noop),
    ]
