# Generated by Django 6.0.2 on 2026-03-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Boshqa tabga o‘tdi'), ('fullscreen_exit', 'Fullscreen’dan chiqdi'), ('right_click', 'Right click qildi'), ('copy_attempt', 'Copy urindi'), ('paste_attempt', 'Paste urindi'), ('cut_attempt', 'Cut urindi'), ('devtools_attempt', 'DevTools urindi')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheating log',
                'verbose_name_plural': 'Cheating logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
